export const profile = {
  username: 'devuser',
  name: 'Marvel Ade',
  title: 'Full-stack Developer',
  location: 'Lagos, Nigeria',
  email: 'hello@devuser.dev',
  avatarInitials: 'MA',
  avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
  avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
  bio:
    'I build polished web experiences with React, Node, accessible UI systems, and practical product thinking.',
  summary:
    'A developer portfolio wrapped in an Ubuntu 22.04 desktop, built for scanning projects, opening apps, and sending messages from one focused workspace.',
  socials: [
    { label: 'GitHub', value: 'github.com/marvelade', href: 'https://github.com/marvelade' },
    { label: 'LinkedIn', value: 'linkedin.com/in/devuser', href: 'https://linkedin.com' },
    { label: 'Twitter', value: 'x.com/marvelade', href: 'https://x.com/marvelade' },
    { label: 'Email', value: 'hello@devuser.dev', href: 'mailto:hello@devuser.dev' },
  ],
  stats: [
    { label: 'Experience', value: '4+ yrs' },
    { label: 'Projects', value: '18' },
    { label: 'Focus', value: 'Web apps' },
  ],
  experience: [
    {
      role: 'Full Stack Developer',
      company: 'Freelance / Product Studio Work',
      period: '2022 - Present',
      summary:
        'Builds portfolio systems, dashboards, and internal tools with React, Node.js, and MongoDB.',
    },
    {
      role: 'Frontend Developer',
      company: 'Independent Client Projects',
      period: '2020 - 2022',
      summary:
        'Shipped responsive marketing sites, admin panels, and interaction-heavy UI prototypes.',
    },
  ],
  education: [
    {
      school: 'Self-Directed Study',
      credential: 'Web Development',
      period: '2019 - Present',
      summary: 'Continuous study of modern JavaScript, UI systems, backend APIs, and deployment workflows.',
    },
    {
      school: 'Online Learning',
      credential: 'Computer Science Fundamentals',
      period: '2018 - 2020',
      summary: 'Focused on programming basics, data structures, and practical software engineering habits.',
    },
  ],
};

export const skills = [
  { group: 'Frontend', items: ['React', 'Tailwind CSS', 'Design systems', 'Accessibility'] },
  { group: 'Backend', items: ['Node.js', 'Express', 'MongoDB', 'REST APIs'] },
  { group: 'Tools', items: ['Git', 'Linux', 'Docker', 'Vite'] },
];

export const skillItems = [
  { name: 'React', icon: 'react', level: 'Advanced', category: 'Frontend' },
  { name: 'Tailwind CSS', icon: 'palette', level: 'Advanced', category: 'Frontend' },
  { name: 'Accessibility', icon: 'shield-check', level: 'Advanced', category: 'Frontend' },
  { name: 'Node.js', icon: 'server', level: 'Advanced', category: 'Backend' },
  { name: 'Express', icon: 'route', level: 'Advanced', category: 'Backend' },
  { name: 'MongoDB', icon: 'database', level: 'Advanced', category: 'Backend' },
  { name: 'Git', icon: 'git-branch', level: 'Advanced', category: 'Tools' },
  { name: 'Linux', icon: 'terminal', level: 'Advanced', category: 'Tools' },
];

export const projects = [
  {
    title: 'Aptly CRM',
    slug: 'aptly-crm',
    type: 'SaaS Dashboard',
    category: 'Full Stack',
    status: 'Completed',
    createdDate: '2026-03-08',
    thumbnail: '',
    description:
      'A quiet operations dashboard with lead scoring, pipeline views, and fast keyboard-led search.',
    stack: ['React', 'Express', 'MongoDB', 'Tailwind'],
    techStack: ['React', 'Express', 'MongoDB', 'Tailwind'],
    impact: 'Cut weekly reporting time by 62%.',
    repo: 'https://github.com/marvelade',
    github: 'https://github.com/marvelade',
    demo: 'https://example.com',
  },
  {
    title: 'Kernel Notes',
    slug: 'kernel-notes',
    type: 'Developer Tool',
    category: 'React + Tailwind',
    status: 'In Progress',
    createdDate: '2026-02-12',
    thumbnail: '',
    description:
      'A Markdown knowledge base with local-first editing, command palette actions, and encrypted sync.',
    stack: ['React', 'IndexedDB', 'Node.js'],
    techStack: ['React', 'IndexedDB', 'Node.js'],
    impact: 'Designed for sub-100ms document switching.',
    repo: 'https://github.com/marvelade',
    github: 'https://github.com/marvelade',
    demo: 'https://example.com',
  },
  {
    title: 'Orange Deploy',
    slug: 'orange-deploy',
    type: 'Automation',
    category: 'APIs',
    status: 'Completed',
    createdDate: '2025-11-22',
    thumbnail: '',
    description:
      'A deployment monitor for small teams with release windows, rollback notes, and service checks.',
    stack: ['Express', 'MongoDB', 'Webhooks'],
    techStack: ['Express', 'MongoDB', 'Webhooks'],
    impact: 'Tracks releases across 12 services.',
    repo: 'https://github.com/marvelade',
    github: 'https://github.com/marvelade',
    demo: 'https://example.com',
  },
  {
    title: 'Markup Studio',
    slug: 'markup-studio',
    type: 'Static Site',
    category: 'HTML',
    status: 'Archived',
    createdDate: '2024-09-14',
    thumbnail: '',
    description:
      'A clean HTML-only portfolio starter with semantic structure, project sections, and contact anchors.',
    stack: ['HTML'],
    techStack: ['HTML'],
    impact: 'Built as a lightweight semantic layout reference.',
    repo: 'https://github.com/marvelade',
    github: 'https://github.com/marvelade',
    demo: 'https://example.com',
  },
  {
    title: 'Yaru Landing',
    slug: 'yaru-landing',
    type: 'Landing Page',
    category: 'HTML + CSS',
    status: 'Completed',
    createdDate: '2025-01-18',
    thumbnail: '',
    description:
      'A responsive landing page with careful spacing, accessible sections, and CSS-only visual polish.',
    stack: ['HTML', 'CSS'],
    techStack: ['HTML', 'CSS'],
    impact: 'Ships without JavaScript and keeps layout shift near zero.',
    repo: 'https://github.com/marvelade',
    github: 'https://github.com/marvelade',
    demo: 'https://example.com',
  },
  {
    title: 'Task Arcade',
    slug: 'task-arcade',
    type: 'Interactive UI',
    category: 'HTML CSS JS',
    status: 'Completed',
    createdDate: '2025-05-04',
    thumbnail: '',
    description:
      'A browser task board with drag interactions, local storage, filtering, and compact status views.',
    stack: ['HTML', 'CSS', 'JavaScript'],
    techStack: ['HTML', 'CSS', 'JavaScript'],
    impact: 'Prototype for lightweight offline productivity flows.',
    repo: 'https://github.com/marvelade',
    github: 'https://github.com/marvelade',
    demo: 'https://example.com',
  },
  {
    title: 'Edge Storefront',
    slug: 'edge-storefront',
    type: 'Frontend',
    category: 'Frontend',
    status: 'In Progress',
    createdDate: '2026-01-05',
    thumbnail: '',
    description:
      'A product browsing interface with fast filters, saved views, and checkout-ready component states.',
    stack: ['React', 'Tailwind CSS', 'Vite'],
    techStack: ['React', 'Tailwind CSS', 'Vite'],
    impact: 'Designed for quick scanning across large catalogs.',
    repo: 'https://github.com/marvelade',
    github: 'https://github.com/marvelade',
    demo: 'https://example.com',
  },
  {
    title: 'Ledger Core',
    slug: 'ledger-core',
    type: 'Backend Service',
    category: 'Backend',
    status: 'Completed',
    createdDate: '2025-08-19',
    thumbnail: '',
    description:
      'A transaction API with validation, pagination, audit logs, and predictable error responses.',
    stack: ['Node.js', 'Express', 'MongoDB'],
    techStack: ['Node.js', 'Express', 'MongoDB'],
    impact: 'Handles account history queries with indexed reads.',
    repo: 'https://github.com/marvelade',
    github: 'https://github.com/marvelade',
    demo: 'https://example.com',
  },
];
